name: viralunity
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake=7.32
  - multiqc=1.15
  - minimap2=2.30
  - samtools=1.23
  - bedtools=2.31
  - pandas=2.0
  - gofasta=1.2
  - kraken2=2.1
  - krona=2.8.1
  - lofreq=2.1.5
  - bcftools=1.21
  - fastp=1.1
  - gsalign=1.0
  - clair3=1.2