name: 'CI'

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: envs/vu_environment.yml
          activate-environment: viralunity
          channels: conda-forge,bioconda,defaults
      
      - name: Run unit tests
        run: make test

      - name: Viralunity install
        run: pip install -e .
      
      - name: Verify 'viralunity' installation working
        run: viralunity -v
